version: '2'
services:
  web:
    image: 46c6ae593b88
    container_name: node
    hostname: node
    ports:
        - "3000:3000"
    expose:
        - "3000"
    volumes:
        - ./node-app:/usr/src/app
    networks:
        net:
            ipv4_address: 172.27.0.2
    tty: true
networks:
    net:
        driver: bridge
        ipam:
            config:
            - subnet: 172.27.0.0/16

